apiVersion: v1
kind: Service
metadata:
  name: jenkins-master-svc
  labels:
    app: jenkins-master
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      NodePort: 30000
  selector:
    app: jenkins-master
