Master:
  ServiceType: ClusterIP
  HostName: jenkins.sirpi.io
  ScriptApproval:
    - "method groovy.json.JsonSlurperClassic parseText java.lang.String"
    - "new groovy.json.JsonSlurperClassic"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods leftShift java.util.Map java.util.Map"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods split java.lang.String"
    - "method java.util.Collection toArray"
    - "staticMethod org.kohsuke.groovy.sandbox.impl.Checker checkedCall java.lang.Object boolean boolean java.lang.String java.lang.Object[]"
    - "staticMethod org.kohsuke.groovy.sandbox.impl.Checker checkedGetProperty java.lang.Object boolean boolean java.lang.Object"
  SecretsFilesSecret: jenkins-secrets
  CredentialsXmlSecret: jenkins-credentials
  Ingress:
    Annotations:
     kubernetes.io/ingress.class: nginx
     kubernetes.io/tls-acme: "true"

    TLS:
     - secretName: jenkins.sirpi.io
       hosts:
         - jenkins.sirpi.io

  InstallPlugins:
  - kubernetes
  - workflow-aggregator
  - credentials-binding
  - git
  - blueocean
  - pipeline-github-lib


Agent:
  Enabled: true
  Image: jenkins/jnlp-slave
  ImageTag: 4.3-7-alpine


Persistence:
  Enabled: true
  ExistingClaim: jenkins
  Annotations: {}
  AccessMode: ReadWriteOnce
  Size: 8Gi


rbac:
  install: true
  serviceAccountName: default
  apiVersion: v1beta1
  roleRef: cluster-admin